export const CRYPTO_CONFIG = {
  PBKDF2_ITERATIONS: 600_000,
  KEY_LENGTH: 256,
  SALT_LENGTH: 32,
  IV_LENGTH: 12,
  ALGORITHM: "AES-GCM" as const,
  HASH: "SHA-256" as const,
  VERIFIER_PLAINTEXT: "NULLPOST_ENCRYPTION_VERIFIER_V1",
} as const
